<?php


require $_SERVER["DOCUMENT_ROOT"] . "/../routes/routes.class.php";
require $_SERVER["DOCUMENT_ROOT"] . "/../helpers/translate.php";

$data = new Translate();
Routes::Add("/", "get", "HomeController::home");
Routes::Add("/generate", "get", "GenerateController::listTypes");
Routes::Add("/generate", "post", "GenerateController::requestListTypes");
Routes::Add("/generate/step2", "get", "GenerateController::step2");
Routes::Add("/generate/step2", "post", "GenerateController::requestStep2");
Routes::Add("/generate/step3", "get", "GenerateController::step3");
Routes::Add("/generate/step3", "post", "GenerateController::requestStep3");
Routes::Add("/generate/step4", "get", "UserController::step4");
Routes::Add("/generate/step6", "get", "GenerateController::step6");
Routes::Add("/generate/createAccount", "post", "UserController::createAccount");
Routes::Add("/generate/login", "post", "UserController::login");
Routes::Add("/generate/createqr", "get", "GenerateController::createqr");
Routes::Add("/site", "get", "TemplateController::init");
Routes::Add("/payment/success", "get", "PaymentsController::success");
Routes::Add("/payment/cancel", "get", "PaymentsController::cancel");
Routes::Add("/generate/step5", "get", "PaymentsController::init");
Routes::Add("/logout", "get", "UserController::logout");
Routes::Add("/BG/", "get", "LanguageController::changeLanguage");
Routes::Add("/CS/", "get", "LanguageController::changeLanguage");
Routes::Add("/DA/", "get", "LanguageController::changeLanguage");
Routes::Add("/DE/", "get", "LanguageController::changeLanguage");
Routes::Add("/EL/", "get", "LanguageController::changeLanguage");
Routes::Add("/EN-GB/", "get", "LanguageController::changeLanguage");
Routes::Add("/EN-US/", "get", "LanguageController::changeLanguage");
Routes::Add("/ET/", "get", "LanguageController::changeLanguage");
Routes::Add("/FI/", "get", "LanguageController::changeLanguage");
Routes::Add("/FR/", "get", "LanguageController::changeLanguage");
Routes::Add("/HU/", "get", "LanguageController::changeLanguage");
Routes::Add("/IT/", "get", "LanguageController::changeLanguage");
Routes::Add("/JA/", "get", "LanguageController::changeLanguage");
Routes::Add("/LT/", "get", "LanguageController::changeLanguage");
Routes::Add("/LV/", "get", "LanguageController::changeLanguage");
Routes::Add("/NL/", "get", "LanguageController::changeLanguage");
Routes::Add("/PL/", "get", "LanguageController::changeLanguage");
Routes::Add("/PT-BR/", "get", "LanguageController::changeLanguage");
Routes::Add("/PT-PT/", "get", "LanguageController::changeLanguage");
Routes::Add("/RO/", "get", "LanguageController::changeLanguage");
Routes::Add("/SK/", "get", "LanguageController::changeLanguage");
Routes::Add("/SL/", "get", "LanguageController::changeLanguage");
Routes::Add("/SV/", "get", "LanguageController::changeLanguage");
Routes::Add("/ZH/", "get", "LanguageController::changeLanguage");
Routes::Add("/faq", "get", "HomeController::faq");
Routes::Add("/conditions", "get", "HomeController::conditions");
Routes::Add("/privacity", "get", "HomeController::privacity");
Routes::Add("/cookies", "get", "HomeController::cookies");
Routes::Add("/contact", "get", "HomeController::contact");
Routes::Add("/cancel", "get", "HomeController::cancel");
Routes::Run();
